apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xev1l-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch

---


apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: xev1l-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: xev1l-cluster-role
  apiGroup: rbac.authorization.k8s.io