apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar-for-my-app
spec:
  mode: sidecar
  config: |
    receivers:
      jaeger:
        protocols:
          grpc:
      prometheus:
              config:
                scrape_configs:
                  - job_name: 'actuator'
                    scrape_interval: 5s
                    metrics_path: '/actuator/prometheus'
                    static_configs:
                      - targets: ['0.0.0.0:8081']
    processors:

    exporters:
          logging:
          jaeger:
            endpoint: http://jaeger-collector-grpc:14250
            insecure: true

    service:
      pipelines:
        traces:
          receivers: [jaeger]
          processors: []
          exporters: [logging]