apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellokub-v1
  namespace: default
  labels:
    app: hellokub
    version: v1
spec:
  selector:
    matchLabels:
      app: hellokub
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: hellokub
        version: v1
    spec:
      containers:
      - name: hellokub
        image: localhost:5000/hellokub:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080